<a href="https://colab.research.google.com/github/SyedHudaif/Python-Workshop/blob/master/Day3_Session2_Pandas%26Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10000

In [1]:
import pandas as pd
ds = pd.Series(x for x in range(10000) if x%2 == 0) 
ls = ds.tolist()
print(ls)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420,

#Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and  after convertion print its type 

In [2]:
import pandas as pd
ds = pd.Series(x for x in range(1000,2000) if x%5 == 0) 
print(ds)
la = ds.tolist()
print(ls)
print(type(ls))

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 3

#Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [3]:
import pandas as pd
ds1 = pd.Series(x for x in range(1,100) if x%2 == 0) 
ds2 = pd.Series(x for x in range(1,100) if x%2 != 0) 
print("Addition\n",ds1+ds2)
print("Subtraction\n",ds1-ds2)
print("Multiplication\n", ds1*ds2)
print("Division\n",ds1/ds2)

Addition
 0       3.0
1       7.0
2      11.0
3      15.0
4      19.0
5      23.0
6      27.0
7      31.0
8      35.0
9      39.0
10     43.0
11     47.0
12     51.0
13     55.0
14     59.0
15     63.0
16     67.0
17     71.0
18     75.0
19     79.0
20     83.0
21     87.0
22     91.0
23     95.0
24     99.0
25    103.0
26    107.0
27    111.0
28    115.0
29    119.0
30    123.0
31    127.0
32    131.0
33    135.0
34    139.0
35    143.0
36    147.0
37    151.0
38    155.0
39    159.0
40    163.0
41    167.0
42    171.0
43    175.0
44    179.0
45    183.0
46    187.0
47    191.0
48    195.0
49      NaN
dtype: float64
Subtraction
 0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
30    1.0
31    1.0
32    1.0
33    1.0
34    1.0
35    1.0
36

#Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
#Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]

In [4]:
import pandas as pd
ds1 = pd.Series(x for x in range(1,637) if x%7 ==0)
ds2 = pd.Series(x for x in range(1,1000) if x%11 ==0)
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)
print("Notequal:")
print(ds1 != ds2)

Series1:
0       7
1      14
2      21
3      28
4      35
     ... 
85    602
86    609
87    616
88    623
89    630
Length: 90, dtype: int64
Series2:
0      11
1      22
2      33
3      44
4      55
     ... 
85    946
86    957
87    968
88    979
89    990
Length: 90, dtype: int64
Compare the elements of the said Series:
Equals:
0     False
1     False
2     False
3     False
4     False
      ...  
85    False
86    False
87    False
88    False
89    False
Length: 90, dtype: bool
Greater than:
0     False
1     False
2     False
3     False
4     False
      ...  
85    False
86    False
87    False
88    False
89    False
Length: 90, dtype: bool
Less than:
0     True
1     True
2     True
3     True
4     True
      ... 
85    True
86    True
87    True
88    True
89    True
Length: 90, dtype: bool
Notequal:
0     True
1     True
2     True
3     True
4     True
      ... 
85    True
86    True
87    True
88    True
89    True
Length: 90, dtype: bool


#Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] 

In [5]:
import numpy as np
import pandas as pd
np_array = np.array([x for x in range(10,1000) if x%10 == 0])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360
 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530 540
 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710 720
 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900
 910 920 930 940 950 960 970 980 990]
Converted Pandas series:
0      10
1      20
2      30
3      40
4      50
     ... 
94    950
95    960
96    970
97    980
98    990
Length: 99, dtype: int64


#Write a Pandas program to convert a given Series to an array.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [6]:
import pandas as pd
ds = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print(ds)
ls = ds.tolist()
print(ls)

0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
['100', '200', '300', '400', '500', 'python', '300.12', '400', 'is', 'great', 'language']


#Write a Pandas program to sort a given Series.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [7]:
import pandas as pd
ds = pd.DataFrame(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'],columns=['col1'])
print("Before sort\n",ds)
ls = ds.sort_values('col1')
print("After sort\n",ls)

Before sort
         col1
0        100
1        200
2        300
3        400
4        500
5     python
6     300.12
7        400
8         is
9      great
10  language
After sort
         col1
0        100
1        200
2        300
6     300.12
3        400
7        400
4        500
9      great
8         is
10  language
5     python


#Write a Pandas program to create a subsets of a given series based on value and condition.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
# value and condtion :  Subset 1 :numbers divisable by 7  Subset 2 : numbers divisable by 5


In [8]:
import pandas as pd
ds = pd.Series([x for x in range(10,1000) if x%10 == 0]) 
sub1 = [x for x in ds if x%7 ==0]
print("divisible by 7\n",sub1)
sub1 = [x for x in ds if x%5 ==0]
print("divisible by 5\n",sub1)

divisible by 7
 [70, 140, 210, 280, 350, 420, 490, 560, 630, 700, 770, 840, 910, 980]
divisible by 5
 [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990]


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [9]:
import pandas as pd
import sympy 
ds = pd.Series([x for x in range(0,1000) if sympy.isprime(x)])
print("Mean\n",ds.mean())
print("SD\n",ds.std())
print("Maximum value : ",ds.max())
print("Minimum value : ",ds.min())

Mean
 453.13690476190476
SD
 298.19241719366255
Maximum value :  997
Minimum value :  2


#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}


In [10]:
import pandas as pd
ls1 = [x for x in range(0,1000) if x%2==1 and x%7!=0]
ls2 = [x for x in range(0,1000) if x%2==0 and x%5!=0]
ls3 = [x for x in range(0,1000) if x%2==1 and x%3!=0]
data = [ls1,ls2,ls3]
df = pd.DataFrame(data) 
df_t = df.T
df_t.columns = ['X', 'Y', 'Z'] 
print(df_t)

         X     Y     Z
0      1.0   2.0   1.0
1      3.0   4.0   5.0
2      5.0   6.0   7.0
3      9.0   8.0  11.0
4     11.0  12.0  13.0
..     ...   ...   ...
424  991.0   NaN   NaN
425  993.0   NaN   NaN
426  995.0   NaN   NaN
427  997.0   NaN   NaN
428  999.0   NaN   NaN

[429 rows x 3 columns]


#Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [11]:
import pandas as pd
ls1 = [x for x in range(0,1000) if x%2==1 and x%7!=0]
ls2 = [x for x in range(0,1000) if x%2==0 and x%5!=0]
ls3 = [x for x in range(0,1000) if x%2==1 and x%3!=0]
data = [ls1,ls2,ls3]
df = pd.DataFrame(data) 
df_t = df.T
df_t.columns = ['X', 'Y', 'Z'] 
print("First ten rows of the data frame:")
print(df_t.iloc[:10])

First ten rows of the data frame:
      X     Y     Z
0   1.0   2.0   1.0
1   3.0   4.0   5.0
2   5.0   6.0   7.0
3   9.0   8.0  11.0
4  11.0  12.0  13.0
5  13.0  14.0  17.0
6  15.0  16.0  19.0
7  17.0  18.0  23.0
8  19.0  22.0  25.0
9  23.0  24.0  29.0


#Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields 
#(movie_metadata.csv file).

In [12]:
import pandas as pd
df = pd.read_csv('/content/movie_metadata.csv')
seventh_movie = df.iloc[6]
print("Details of the third moviee:")
print(seventh_movie)

Details of the third moviee:
color                                                                    Color
director_name                                                        Sam Raimi
num_critic_for_reviews                                                     392
duration                                                                   156
director_facebook_likes                                                      0
actor_3_facebook_likes                                                    4000
actor_2_name                                                      James Franco
actor_1_facebook_likes                                                   24000
gross                                                               3.3653e+08
genres                                                Action|Adventure|Romance
actor_1_name                                                      J.K. Simmons
movie_title                                                      Spider-Man 3 
num_voted_users        

#Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields 

In [13]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/movie_metadata.csv')
print("sorted by title_year")
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values('title_year')
print("DataFrame based on release date.")
print(result)


sorted by title_year
DataFrame based on release date.
     num_user_for_reviews language  ...     budget title_year
4810                   88      NaN  ...   385907.0     1916.0
4958                    1      NaN  ...   100000.0     1920.0
4885                   45      NaN  ...   245000.0     1925.0
2734                  413   German  ...  6000000.0     1927.0
4812                   71  English  ...   379000.0     1929.0
...                   ...      ...  ...        ...        ...
4798                  379  English  ...        NaN        NaN
4803                   82  English  ...        NaN        NaN
4819                  323  English  ...        NaN        NaN
4869                   59  English  ...        NaN        NaN
5039                  359  English  ...        NaN        NaN

[5043 rows x 6 columns]


#Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [14]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
df1 = df[['name','score','attempts']]
df1.head(10)

First three rows of the data frame:


name  score  attempts
a  Anastasia   12.5         1
b       Dima    9.0         3
c  Katherine   16.5         2
d      James    NaN         3
e      Emily    9.0         2
f    Michael   20.0         3
g    Matthew   14.5         1
h      Laura    NaN         1
i      Kevin    8.0         2
j      Jonas   19.0         1

#Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.(movie_metadata.csv)

In [15]:
import pandas as pd
xyz = pd.read_csv('/content/movie_metadata.csv') 
df = xyz[['language','country','duration']]
print(df.head(10))

  language country  duration
0  English     USA     178.0
1  English     USA     169.0
2  English      UK     148.0
3  English     USA     164.0
4      NaN     NaN       NaN
5  English     USA     132.0
6  English     USA     156.0
7  English     USA     100.0
8  English     USA     141.0
9  English      UK     153.0


#Write a Pandas program to find the mean and standard deviation, maximum and minimum of the data of 50 students Python marks stored in a CSV file called Python_mark.csv( you have to create the file yourself like rollno,mark for 50 records)

In [16]:
import pandas as pd
df = pd.DataFrame({'roll number':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50],'marks':[20,22,23,24,25,26,27,12,13,15,23,24,23,21,12,13,14,15,30,24,25,26,27,28,29,30,22,22,22,22,23,23,23,23,23,23,24,24,24,25,26,26,27,27,27,27,27,26,27,23]})
print(df.mean())
print(df.std())
print(df.min())
print(df.max())
df.to_csv('python_marks',index=False)
df1 = pd.read_csv('python_marks')
print(df1)
print(df1.mean())
print(df1.std())
print(df1.min())
print(df1.max())

roll number    25.50
marks          23.14
dtype: float64
roll number    14.577380
marks           4.558061
dtype: float64
roll number     1
marks          12
dtype: int64
roll number    50
marks          30
dtype: int64
    roll number  marks
0             1     20
1             2     22
2             3     23
3             4     24
4             5     25
5             6     26
6             7     27
7             8     12
8             9     13
9            10     15
10           11     23
11           12     24
12           13     23
13           14     21
14           15     12
15           16     13
16           17     14
17           18     15
18           19     30
19           20     24
20           21     25
21           22     26
22           23     27
23           24     28
24           25     29
25           26     30
26           27     22
27           28     22
28           29     22
29           30     22
30           31     23
31           32     23
32           33     2

#Write a Pandas program to sort the DataFrame based on country and language from dataset of movie_metadata.csv

In [17]:
import pandas as pd
df = pd.read_csv('/content/movie_metadata.csv')
small_df = df[['country','language']]
print("DataFrame based on country and language")
print(small_df.sort_values('country'))
print(small_df.sort_values('language'))

DataFrame based on country and language
          country language
4735  Afghanistan     Dari
4450    Argentina  Spanish
4666    Argentina  Spanish
4415    Argentina  Spanish
4000    Argentina  Spanish
...           ...      ...
4             NaN      NaN
279           NaN      NaN
2370          NaN  English
3397          NaN  English
4021          NaN  English

[5043 rows x 2 columns]
        country    language
5031    English           8
3504  Australia  Aboriginal
377          UK  Aboriginal
4393     France      Arabic
4580    Germany      Arabic
...         ...         ...
4409        USA         NaN
4630        USA         NaN
4810        USA         NaN
4885        USA         NaN
4958        USA         NaN

[5043 rows x 2 columns]


#Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [18]:

import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 
y = np.array(x[1:3])
y

Original Array:
[[0.67635033 0.04619368 0.42861661 0.7760897 ]
 [0.80765538 0.30774307 0.82560532 0.44522272]
 [0.88865306 0.26635118 0.05231445 0.84863216]
 [0.41568764 0.40258062 0.97026971 0.59930098]]


array([[0.80765538, 0.30774307, 0.82560532, 0.44522272],
       [0.88865306, 0.26635118, 0.05231445, 0.84863216]])

#Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [19]:

import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.17907892 0.09732678 0.57465349 0.93411135 0.60241814 0.54842874
  0.97039444 0.34622586 0.32677554 0.14175113]
 [0.82209294 0.66982451 0.97718436 0.73904539 0.6301796  0.51354083
  0.18721641 0.58261627 0.09691379 0.25035257]
 [0.24413571 0.18759284 0.34136755 0.29187376 0.19938487 0.41031862
  0.40113708 0.09552893 0.84564026 0.85278005]
 [0.67888688 0.0784944  0.34351696 0.15328225 0.05624853 0.6430007
  0.40201662 0.03390121 0.91264764 0.55655868]
 [0.17042785 0.41207436 0.26623002 0.77299696 0.75977042 0.93707178
  0.80478548 0.02908237 0.75929726 0.7795223 ]
 [0.05580533 0.45113815 0.45951633 0.16095725 0.98947782 0.6561364
  0.12783507 0.34626938 0.65887524 0.41302344]
 [0.16264233 0.6473891  0.57124631 0.64885778 0.24685371 0.33157649
  0.02168395 0.53665113 0.10116648 0.24002697]
 [0.41509131 0.26916417 0.56408681 0.00357086 0.2941157  0.49144659
  0.83726246 0.42780188 0.02926065 0.55837108]
 [0.08351991 0.22737774 0.8231364  0.07987738 0.52575637 0.0531110

#Write a NumPy program to generate 8 random integers between 100 and 300

In [20]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[179 195 162 199 213 290 160 146]


#Write a NumPy program to create a random integer nos of size 20 and sort it

In [21]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)


Original array:
[0.75517922 0.53243689 0.75477993 0.18122094 0.50556048 0.76448094
 0.23448279 0.53604533 0.92759146 0.55768894 0.18807757 0.48515449
 0.1188332  0.80932228 0.82567941 0.57563488 0.80226285 0.34554091
 0.35119739 0.42658976]
Sorted array:
[0.1188332  0.18122094 0.18807757 0.23448279 0.34554091 0.35119739
 0.42658976 0.48515449 0.50556048 0.53243689 0.53604533 0.55768894
 0.57563488 0.75477993 0.75517922 0.76448094 0.80226285 0.80932228
 0.82567941 0.92759146]
