<a href="https://colab.research.google.com/github/SyedHudaif/Python-Workshop/blob/master/Day3_Session2_NumpyExamples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Write a NumPy program to generate five random numbers from the normal distribution.

In [1]:
import numpy as np
x = np.random.normal(size=5)
print(x)


[ 0.18145459  0.79936142 -0.21170271  0.15849928 -0.34056183]


#Write a NumPy program to generate six random integers between 10 and 30

In [2]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[11 25 15 27 12 22]


#Write a NumPy program to create a 3x3x3 array with random values.

In [3]:
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.08700053 0.78514291 0.89984407]
  [0.39274103 0.22734818 0.89551155]
  [0.43728296 0.1493896  0.03330599]]

 [[0.31077447 0.8690588  0.30168375]
  [0.0250047  0.72942599 0.13615814]
  [0.5242799  0.05974637 0.20283819]]

 [[0.77179394 0.81819694 0.77156163]
  [0.65803564 0.33716993 0.24342343]
  [0.86713976 0.95501997 0.53578656]]]


#Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

In [4]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.25819538 0.1337778  0.60333716 0.59517199 0.54521973]
 [0.81110134 0.68164378 0.92696581 0.1922512  0.73301269]
 [0.78758206 0.57447474 0.94698687 0.88290667 0.16767579]
 [0.10689435 0.38755004 0.47999747 0.88393791 0.61563652]
 [0.24147903 0.64512072 0.96109058 0.13911451 0.52272665]]
Minimum and Maximum Values:
0.10689435080972742 0.9610905831419387


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [5]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)


Original array: 
[[0.13135753 0.64142637 0.78406074 0.14758573]
 [0.40271978 0.87662831 0.19005549 0.19612686]
 [0.09415056 0.47944954 0.10143001 0.1048474 ]
 [0.79297422 0.49456397 0.43541322 0.92509878]
 [0.91514014 0.1347056  0.99581511 0.652401  ]
 [0.25305186 0.6896164  0.63046458 0.19756944]
 [0.01726856 0.91885799 0.26206704 0.73605944]
 [0.11952947 0.13525522 0.12650019 0.46936515]
 [0.46733776 0.4122252  0.34337756 0.88387335]
 [0.94961731 0.36735495 0.6218434  0.24282281]]
First 5 rows of the above array:
[[0.13135753 0.64142637 0.78406074 0.14758573]
 [0.40271978 0.87662831 0.19005549 0.19612686]
 [0.09415056 0.47944954 0.10143001 0.1048474 ]
 [0.79297422 0.49456397 0.43541322 0.92509878]
 [0.91514014 0.1347056  0.99581511 0.652401  ]]
First 3 columns of the above array:
[[0.13135753 0.64142637 0.78406074 0.14758573]
 [0.40271978 0.87662831 0.19005549 0.19612686]
 [0.09415056 0.47944954 0.10143001 0.1048474 ]
 [0.79297422 0.49456397 0.43541322 0.92509878]
 [0.91514014 0.1347

#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).

In [6]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[9 6 5 1 2 8 7 4 0 3]
Same result using permutation():
[9 6 7 5 4 0 8 1 3 2]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [7]:
import numpy as np
x=np.arange(10)
np.random.randint(1, size=x)
print (x)


[0 1 2 3 4 5 6 7 8 9]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [8]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[8 1 5 0 3 4 6 9 2 7]
[0 1 2 3 4 5 6 7 8 9]
